# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'
  
steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node'

- script: npm install -g newman-reporter-junitfull
  displayName: 'Install Newman and reporter'

- script: echo $(Build.ArtifactStagingDirectory)
  displayName: 'Print Build Artifact Stating Directory'

- script: newman run Postman_API_TestProject.postman_collection.json -e AugustaCorp.postman_environment.json -r cli,junitfull --reporter-junitfull-export JUnitReport.xml
  displayName: 'Run API Test'

- task: PublishTestResults@2
  displayName: 'Publish Unit Test Results' 
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'

- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'Augusta Team Chennal'
    method: 'POST'
    body: |
      {
      "@context": "http://schema.org/extensions",
      "@type": "MessageCard",
      "Title": "Metric Alert",
      "text":   "<p style='color:red;font-weight:bold'>Rams, UBFFIt service CPU utilization spikes to 90%</p>. [Read the report here](http://test.io)" }
    waitForCompletion: 'false'