# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- script: |
    echo BuildConfiguration is $(BuildConfiguration)
    echo system.defaultworkingdirectory is $(system.defaultworkingdirectory)
    echo build.artifactstagingdirectory is $(build.artifactstagingdirectory)

- script: ls
  displayName: 'Get the file'
  
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node'

- script: npm install
  displayName: 'Install application dependencies' 

- script: npm install -g newman-reporter-junitfull
  displayName: 'Install Newman and reporter'

- script: echo $(Build.ArtifactStagingDirectory)
  displayName: 'Print Build Artifact Stating Directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'API Test Scripts'
    publishLocation: 'Container'
  displayName: 'Publish application artifacts'

- script: ls
  displayName: 'Get the file'
